name: Build firmware with xc8

on:
  push:
    branches: [ "master", "red-pulse" ]
  workflow_dispatch:
  
jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v4

    - name: Install deps & xc8
      run: |
        sudo dpkg --add-architecture i386
        sudo apt update
        sudo apt install -y libc6:i386 libx11-6:i386 libxext6:i386 libstdc++6:i386 libexpat1:i386 libusb-1.0-0-dev wget sudo make
        sudo apt clean
        sudo apt autoremove --purge -y
        wget -nv -O /tmp/xc8 "https://ww1.microchip.com/downloads/aemDocuments/documents/DEV/ProductDocuments/SoftwareTools/xc8-v2.40-full-install-linux-x64-installer.run"
        chmod +x /tmp/xc8
        sudo /tmp/xc8 --mode unattended --unattendedmodeui none --netservername localhost --LicenseType FreeMode --prefix "/opt/microchip/xc8"
        wget -nv -O /tmp/picdfp.zip "https://packs.download.microchip.com/Microchip.PIC10-12Fxxx_DFP.1.7.178.atpack"
        sudo mkdir /opt/microchip/dfp
        sudo unzip /tmp/picdfp.zip -d /opt/microchip/dfp
        rm /tmp/xc8 /tmp/picdfp.zip
        ls -l /opt/microchip/dfp/xc8
        

    - name: Build
      run: |        
        /opt/microchip/xc8/bin/xc8 -mcpu=10F200 -mdfp=/opt/microchip/dfp/xc8 -v -O2 -maddrqual=ignore -v -mwarn=0 -Wa,-a -Wl,--data-init -mno-osccal -mresetbits -msave-resetbits -mno-download -mno-stackcall -mno-config -mno-default-config-bits -std=c90 -mc90lib -mstack=compiled:auto flashlight.c || /bin/true
        mkdir build
        /opt/microchip/xc8/bin/xc8 -mcpu=10F200 -mchip=10F200 -mdfp=/opt/microchip/dfp/xc8 -v -O2 -maddrqual=ignore -v -mwarn=0 -Wa,-a -Wl,--data-init -mno-osccal -mresetbits -msave-resetbits -mno-download -mno-stackcall -mno-config -mno-default-config-bits -std=c90 -mc90lib -mstack=compiled:auto -o build/flashlight.elf flashlight.c || /bin/true
        ls -l . ./build
